[[constraint]]
  name = "github.com/dgrijalva/jwt-go"
  version = "3.2.0"

[[constraint]]
  name = "github.com/alexellis/hmac"
  version = "1.2"

[[constraint]]
  name = "github.com/openfaas/faas-provider"
  version = "v0.15.0"

[[constraint]]
  name = "github.com/openfaas/openfaas-cloud"
  version = "0.13.0"

[prune]
  go-tests = true
  unused-packages = true
